FROM fedora:rawhide

# --nogpgcheck: Ignore transient(?) package signature failures
RUN dnf --nogpgcheck -y install \
        /usr/bin/appstream-util \
        /usr/bin/cpio \
        /usr/bin/bzip2 \
        /usr/bin/desktop-file-validate \
        /usr/bin/groff \
        /usr/bin/gtbl \
        /usr/bin/make \
        /usr/bin/man \
        /usr/bin/perl \
        /usr/bin/python \
        /usr/bin/readelf \
        /usr/bin/xz \
        python3-enchant \
        python3-flake8 \
        python3-flake8-import-order \
        python3-magic \
        python3-pytest \
        python3-devel rpm-build

WORKDIR /usr/src/rpmlint
COPY . .
