FROM fedora:33

# --nogpgcheck: Ignore transient(?) package signature failures
RUN dnf --nogpgcheck -y install \
        /usr/bin/appstream-util \
        /usr/bin/cpio \
        /usr/bin/bzip2 \
        /usr/bin/desktop-file-validate \
        /usr/bin/python3 \
        /usr/bin/readelf \
        /usr/bin/ldd \
        /usr/bin/c++filt \
        /usr/bin/xz \
        dash \
        devscripts-checkbashisms \
        glibc \
        glibc.i686 \
        hunspell-en \
        hunspell-cs \
        python3-setuptools \
        python3-enchant \
        python3-magic \
        python3-rpm \
        python3-pybeam \
        python3-pytest \
        python3-pytest-cov \
        python3-pytest-flake8 \
        python3-pytest-xdist \
        python3-flake8 \
        python3-flake8-import-order \
        python3-pyxdg \
        python3-toml \
        python3-zstd \
        rpm-build \
        sqlite \ 
        systemd-rpm-macros

WORKDIR /usr/src/rpmlint
VOLUME /usr/src/rpmlint
