FROM centos:7

RUN yum -y install epel-release
RUN yum -y install \
        /bin/cpio \
        /usr/bin/bzip2 \
        /usr/bin/desktop-file-validate \
        /usr/bin/groff \
        /usr/bin/gtbl \
        /usr/bin/make \
        /usr/bin/man \
        /usr/bin/perl \
        /usr/bin/python \
        /usr/bin/readelf \
        /usr/bin/xz \
        python-pip \
        python-enchant \
        python-magic \
        python-rpm

# workaround of too old setuptools/pytest
RUN pip install setuptools --upgrade

WORKDIR /usr/src/rpmlint
COPY . .
