FROM centos:6

RUN yum -y install \
        /bin/cpio \
        /usr/bin/bzip2 \
        /usr/bin/desktop-file-validate \
        /usr/bin/groff \
        /usr/bin/gtbl \
        /usr/bin/make \
        /usr/bin/man \
        /usr/bin/py.test \
        /usr/bin/readelf \
        /usr/bin/xz \
        python-enchant \
        python-magic

WORKDIR /usr/src/rpmlint
COPY . .
