.\"
.\" (C) Copyright 2014, Arturo Borrero Gonzalez <arturo@debian.org>,
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.TH RPMDIFF 1 "February  6, 2014"

.SH NAME
rpmdiff \- search for differences between two RPM packages
.SH SYNOPSIS
.B rpmdiff
.RI [<options>] " <old_RPM> <new_RPM>"
.SH DESCRIPTION
The \fBrpmdiff\fP tool shows differences between two RPM packages.

.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-i, \-\-ignore\fR=\fIproperty\fR
File property to ignore when calculating differences (may be used
multiple times).
.br
Valid values are:
.nf
 S (size)
 M (mode)
 5 (checksum)
 D (device)
 N (inode)
 L (number of links)
 V (vflags)
 U (user)
 G (group)
 F (digest)
 T (time)
.fi
.SH SEE ALSO
.BR rpmlint (1),
.BR rpm (1)

.SH AUTHOR
Originally written by Frédéric Lepied, modified and maintained by
numerous contributors since.
.br
This manual page was written by Arturo Borrero González
<arturo@debian.org>, and is free/libre documentation
(GPL-2+).
