#!/bin/sh
#############################################################################
# File		: rpmlint
# Package	: rpmlint
# Author	: Frederic Lepied
# Created on	: Mon Sep 27 19:20:18 1999
# Version	: $Id$
# Purpose	: main entry point: process options, load the checks and run
#		the checks.
#############################################################################

PYTHONPATH=${PYTHONPATH=.}

PYTHONPATH=${PYTHONPATH}:/usr/share/rpmlint

exec python -O /usr/share/rpmlint/rpmlint.py $*

# rpmlint ends here
