non-etc-or-var-file-marked-as-conffile="""
A file not in /etc or /var is marked as being a configuration file (%config).
Please put your configuration files in /etc or /var.
"""
conffile-without-noreplace-flag="""
A configuration file is stored in your package without the noreplace flag.
This flag tells RPM not to overwrite or replace a configuration file to protect
local modifications.
A way to resolve this is to put the following in your SPEC file:
%config(noreplace) /etc/your_config_file_here
"""
