invalid-version="""
The version string must not contain the pre, alpha, beta or rc suffixes
because when the final version will be out, you will have to use an Epoch tag
to make the package upgradable. Instead put it in the release tag, prefixed
with something you have control over.
"""
spelling-error="""
The value of this tag appears to be misspelled. Please double-check.
"""
no-packager-tag="""
There is no Packager tag in your package. You have to specify a packager
using the Packager tag. Ex: Packager: John Doe <john.doe@example.com>.
"""
invalid-packager="""
The packager email must end with an email compatible with the Packager
option of rpmlint. Please change it and rebuild your package.
"""
no-version-tag="""
There is no Version tag in your package. You have to specify a version using
the Version tag.
"""
no-release-tag="""
There is no Release tag in your package. You have to specify a release using
the Release tag.
"""
no-name-tag="""
There is no Name tag in your package. You have to specify a name using the
Name tag.
"""
non-coherent-filename="""
The file which contains the package should be named <NAME>-<VERSION>-<RELEASE>.<ARCH>.rpm.
"""
no-major-in-name="""
The major number of the library isn't included in the package's name.
"""
description-shorter-than-summary="""
The package description should be longer than the summary.
"""
no-provides="""
Your library package doesn't provide the -devel name without the major
version included.
"""
no-summary-tag="""
There is no Summary tag in your package. You have to describe your package
using this tag.
"""
summary-on-multiple-lines="""
Your summary must fit on one line.
"""
summary-not-capitalized="""
Summary doesn't begin with a capital letter.
"""
summary-ended-with-dot="""
Summary ends with a dot.
"""
summary-has-leading-spaces="""
Summary begins with whitespace which will waste space when displayed.
"""
no-description-tag="""
The description of the package is empty or missing.
"""
tag-in-description="""
Something that looks like a tag was found in the package's description.
This may indicate a problem where the tag was not actually parsed as a tag
but just textual description content, thus being a no-op.  Verify if this is
the case, and move the tag to a place in the specfile where %description
won't fool the specfile parser, and rebuild the package.
"""
no-group-tag="""
There is no Group tag in your package. You have to specify a valid group
in your spec file using the Group tag.
"""
no-changelogname-tag="""
There is no %changelog tag in your spec file. To insert it, just insert a
'%changelog' in your spec file and rebuild it.
"""
no-version-in-last-changelog="""
The latest changelog entry doesn't contain a version. Please insert the
version that is coherent with the version of the package and rebuild it.
"""
incoherent-version-in-changelog="""
The latest entry in %changelog contains a version identifier that is not
coherent with the epoch:version-release tuple of the package.
"""
changelog-time-overflow="""
The timestamp of the latest entry in %changelog is suspiciously far away in
the past.
"""
changelog-time-in-future="""
The timestamp of the latest entry in %changelog is in the future.
"""
no-license="""
There is no License tag in your spec file. You have to specify one license
for your program (eg. GPL-3.0-only).
"""
obsolete-not-provided="""
If a package is obsoleted by a compatible replacement, the obsoleted package
should also be provided in order to not cause unnecessary dependency breakage.
If the obsoleting package is not a compatible replacement for the old one,
leave out the Provides.
"""
invalid-dependency="""
An invalid dependency has been detected. It usually means that the build of
the package was buggy.
"""
no-epoch-tag="""
There is no Epoch tag in your package.
"""
unreasonable-epoch="""
The value of your Epoch tag is unreasonably large (> 99).
"""
no-epoch-in-dependency="""
Your package contains a versioned dependency without an Epoch.
"""
devel-dependency="""
Your package has a dependency on a devel package but it's not a devel
package itself.
"""
invalid-build-requires="""
Your source package contains a dependency not compliant with the lib64
naming. This BuildRequires dependency will not be resolved on lib64 platforms
(eg. amd64).
"""
explicit-lib-dependency="""
You must let rpm find the library dependencies by itself. Do not put
unneeded explicit Requires: tags.
"""
useless-provides="""
This package provides multiple times the same capacity.
This means versioned and unversioned symbols are provided at once
thus one overshadowing the other. I.e. 'foo' and 'foo = 1.0'.
"""
tag-not-utf8="""
The character encoding of the value of this tag is not UTF-8.
"""
requires-on-release="""
This rpm requires a specific release of another package.
"""
no-url-tag="""
The URL tag is missing.
"""
name-repeated-in-summary="""
The name of the package is repeated in its summary. Make the summary
brief and to the point without including redundant information in it.
"""
enchant-dictionary-not-found="""
A dictionary for the Enchant spell checking library is not available for
the language given in the info message.
"""
self-obsoletion="""
The package obsoletes itself. This is known to cause errors in various
tools and should thus be avoided, usually by using appropriately versioned
Obsoletes and/or Provides and avoiding unversioned ones.
"""
unexpanded-macro="""
This tag contains something that looks like an unexpanded macro; this is
often the sign of a misspelling. Please check your specfile.
"""
private-shared-object-provides="""
A shared object soname provides is provided by a file in a path from which
other packages should not directly load shared objects from. Such shared
objects should thus not be depended on and they should not result in provides
in the containing package. Get rid of the provides if appropriate, for example
by filtering it out during build. Note that in some cases this may require
disabling rpmbuild's internal dependency generator.
"""
devel-package-with-non-devel-group="""
The package ends with -devel but does not have a RPM group starting with
Development/.
"""
no-pkg-config-provides="""
The package installs a .pc file but does not provide pkgconfig(..) provides.
The most likely reason for that is that it was built without BuildRequires: pkgconfig.
Please double check your build dependencies."""
invalid-license-exception="""
The ' with <x> ' license exception of the License tag was not recognized.
"""
forbidden-controlchar-found="""
This package contains tags which contain forbidden control characters.
These are all ASCII characters with a decimal value below 32, except TAB(9),
LF(10) and CR(13)
"""
summary-too-long="""
This package has a summary line greater than 79 characters. Keep the summary below the character limit.
"""
description-line-too-long="""
This package has a description line of length greater than 79 characters. Break the line into multiple lines to remove the warning.
"""
